"""
Validation package for the Industrial Energy Transition Optimizer.
"""

from .validation_engine import (
    AssumptionRecord,
    CalibrationValidationError,
    ConflictRecord,
    ConflictValidationError,
    EvidenceValidationError,
    ParameterCandidate,
    ParameterValidationError,
    UnitSystem,
    UnitValidationError,
    ValidationEngine,
    ValidationEngineError,
    ValidationIssue,
    ValidationReport,
    ValidationResult,
    convert_energy,
    kg_to_tonnes,
    kgco2e_to_tco2e,
    kwh_to_mj,
    mj_to_gj,
    mj_to_kwh,
    run_self_test,
    tj_to_mj,
)

__all__ = [
    "AssumptionRecord",
    "CalibrationValidationError",
    "ConflictRecord",
    "ConflictValidationError",
    "EvidenceValidationError",
    "ParameterCandidate",
    "ParameterValidationError",
    "UnitSystem",
    "UnitValidationError",
    "ValidationEngine",
    "ValidationEngineError",
    "ValidationIssue",
    "ValidationReport",
    "ValidationResult",
    "convert_energy",
    "kg_to_tonnes",
    "kgco2e_to_tco2e",
    "kwh_to_mj",
    "mj_to_gj",
    "mj_to_kwh",
    "run_self_test",
    "tj_to_mj",
]